language: node_js
node_js: '9'
sudo: required
os: linux
dist: trusty
addons:
  chrome: stable
  firefox: latest
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build:static
deploy:
  provider: s3
  access_key_id: AKIAJ6E6HESGQGVUXR6A
  secret_access_key:
    secure: wgEG5cjWAhmvQToSgLIVqJegsO0CJVosADsVYc59JDD74oxvqPMa4pZzFfHnvbnoh3Es820S4oHv6nzAKUH87yL282pcts8MORbncwW4RaWijrSvAYTSyJrhwSeC03U5h3Ok9Nmze7zw3X3UBYPTJk5KIsEzAB0Tig1B7x2IKaL3H2e6+MbELhCpOPqN0IgdLlwZ1VyurhEkcOqcrsIUNTxhKrovbZvhr0l3LQxwH/gENoQ6wizuxNPnEAceaeAO5zfSSGOMDEigbxtZQWasGaBrgU80tUCSBmcd9JFO0+BTQCUmH457XXSgEjGmkzPib7bdWcZdEIV+YYa9Awofgpk9R6cf5YS9CBeWw5qzFG9Irp19yjMiG9Oqpi3I5nFVUbHVCAZXVTWSdaNWEz07oT5D+Uv5c9mqMylZj5uCFSezZZFk4HFE5+6E4RaEY8gjYwqnlnP4k4ZubT6dvcLlSZ4eY3wldQCy8/V+y1LNcESUMcFHyfAVHd9bpbOEWPhD69qnOtr7RnLaluo71yrfff9fYaPudFlDXgvMs4j4yfCXCHA9pROf2wmOJ6mDSl3q8vsLvpCw6LJurlWDuO0jXMlKHEcZmduUl4chgmYaLcsqzwoRVlZQGsmwHxz1ClsYCDEi+8Lp1NbaEdYpgDdltcv1PVAcSLcrjnsHb1qHzdg=
  bucket: fitnessapp.tld
  region: eu-west-2
  skip_cleanup: true
  local-dir: build/es6-bundled
  acl: public_read
  on:
    repo: bobbydeveaux/fitnessapp2
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E2NJ8TIWQ1HARF --paths "/*"
