language: node_js
before_script:
- npm install
script:
- npm run test
- npm run build:static
env:
  global:
  - secure: C+/z9HB1amzxgntbpkNhjcWeYFt6uagVAp2TuceInyzCpwD8A9mOG+X3pfBX8A0OJnKchSduXbcUzcg8Rw2ZVR/RZajkzWUnInFNeFm4WMgHZFQxc+pHq9o5UyCw+Q237+S5IdC+WI0lfAGh3+5OeGvS+JoC3jUarYb6UlCybgfkqA+Zo0wy6Xyjisb3vYKPnmmF+Ki5fkzwLqpkcqQI3zZQZimTZHNwGOJO6ib2uEEjaCVhvG1XKDlF8M+07arE97hKOJEEKIHHPOaPtABw634OfwbiS5lPHlb626VD+ry08P1FH7mg3XM+XdUS7T+o3Lb2RScjA5jetF27s2E9mK467zIw60kC5e8eDx8/uJWlx/c3jT4nQQ+epjTp7M5lbOQBYiQttGureaWHSVVvUJKTrSN8CxceV7Zmia1N9dtC3o2CEDZyrbJ5+2tR8POkUZkz5XHNhHg0/U/vq0dm3LjhOGfyKCqD4o1qS2ytdzPVu2fwHdD63NxU1pKPeYNcO3aKASTgUJpPWA4j/JQWWNF/HTUU6NMO3ihKxX+ZeenX/wtvSrurNIFhIqf81hr0iRYVH+pMOZ7shfr65w6GgllQjO2gFz8IZyc0t9I5CJnOVyhHfgdVj4XgeTHaxDalYE/eB/ny1unxbG/c+6v06pHWJ9HNXFd5VXPTmtNu1m8=
  - secure: MIqRhLuXEh4qKMvVnbqs2jAtwsGgnl8qLYRNGKeG5eUf3aJT86FJefcccddVAipNun10fnkSkNd2rpNb/G8Htxvyg9lYiOeCDOvxsaDtYwxvz1WGk2u5kRUjkfyb2LVzUV0MCUSiR+o/9qUXy5TVcwrzAN/4Jin8diMPVkuektP5xhyVm1BAMufn+IcX56xtkT123Egz1Y0N47TKB4rEqhVUazYvMy2Vq2Xs2NIpVT2v8+91UzRLCeESIKKPFfZvdgVHovqKiKmsXLMsGTsAKT6FjimSmKvknC4iR7B3CiQQwoo0GIJjd/QKy35S3wMUoZEy+WpN8hBuKoJLg2GtaVmsV1MEAyKBFtMRPQwUTSPSxz5RQzVYKby9TsOKulFbsfk1jRzAlJSc4USSXO7/HH/vcTF0NZJhqvZAo8mX43UqQSmOEo6vobEASM8I5lysQnuqjrDTowg8Wou7a0yhIaKiGBhf5Yy61mSqURNBXCpRHR75SDr2/9qtqU8hfH6PqCuLHtQ0eEhNzfcjo8fPRcAx2QWPmmnOpDAZcxFvVGlkiM5aOFlRiPbGLFADkzm1uDh7GYfSChoLoEhM/MJMxl0OeLIcKpsgXUjrQv2KdJCVtbu610jMlH98J5GsfoA7SkKUn8DYujkuhaHBqYKLjZ7tCVLXsoMZqJcQf7W5Q3g=
deploy:
  provider: s3
  access_key_id: AKIAIGKXVNFPSU7YOGYQ
  secret_access_key:
    secure: vm/VGebBkLd8BR1uyZJ/p6KUpjlq37s7wDlv0I+NcqQYuM0/Lf1nDxkVssv5oGPRyXPsWZIzqJH9fHqxhFfHcZ96uuyA9e7HP2iXs0Dx0JcISARom2g5YFBHIJdTCja9gpSLHbowRfYfEmconhAyox421wmK+Owt0j7p9VnmrvaVIamcsQSC1QNj8ACExZQDx9lOig3HPfhhqSlRKsJJz+cZAuqcvOgT36V3xGrg8tPMtHr7Cj1ipyqzzjfGkfYTkailjQJcZGHtTGVfKdKadRc4+S4As+C7+hTYoafc1V40Yfw/q/0SnYC9qPcgPh8TJOOXN8dkJr+0DlbsNa6rbjX1sK9uP3xgY6XNqaGkirEse02l1GOYZliqHR1WT/QmIvZY+kMFqQ72xkRQACXfloU2xPjX7kW0DsmDbw2UFxsOW/yISHWY35P0G6vNYA00jmu4QGZqMT64nqk1NMefKWb/UJ5V91LurOtZIjkP9Gu4zpY8GFMcbM33e2v+xUtlI99YdEwl7u4jJ//nZftz3beGAQSH6PU/q7BlTVOE9W+uItYi7wdn9Jv8hKNCp2nzQT7WOQ5vCAwHR6SaaBsxery2NXy5cDLLJFKF9CelbnZqCZd+H7uvIKrS8u1R6e3sLtAbAaMooF1QuWB/lGSYL7lEOdRCOavsSqQI1th2swI=
  bucket: fitnessapp.tld
  region: eu-west-2
  skip_cleanup: true
  local-dir: build
  acl: public_read
  on:
    repo: bobbydeveaux/fitnessapp2
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id ERXCI0CPDJBBR --paths "/*"